app/urls.py
from django.urls import path, include, re_path
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib import admin

admin.autodiscover()
admin.site.login = login_required(admin.site.login)


app_name = 'app'


urlpatterns = [
    re_path(r'^dashboard/(?P<id>[a-zA-Z0-9]{10})/$', views.Dashboard.as_view(), name='dashboard'),


    path('api/download', views.DownloadPDF.as_view(), name="download"),

    path('projects', views.AppPanel.as_view(), name="app_panel"),
    path('api/generate_text', views.GenerateTextView.as_view(), name="generate_text"),
    path('api/generate_suggestion', views.GenerateSuggestion.as_view(), name="generate_suggestion"),

    path('api/generate_image', views.GenerateImage.as_view(), name="generate_image"),
    path('api/generate_all_images', views.GenerateAllImages.as_view(), name="generate_all_images"),
    path('api/update_text', views.UpdateText.as_view(), name="update_text"),


    path('api/create_board', views.CreateBoard.as_view(), name="create_board"),
    path('api/create_board_slide', views.CreateBoardSlide.as_view(), name="create_board_slide"),



    path('api/get_all_boards', views.GetAllBoards.as_view(), name="get_all_boards"),
    path('api/get_all_slides', views.GetAllSlides.as_view(), name="get_all_slides"),



    path('api/delete_board', views.DeleteBoard.as_view(), name="delete_board"),
    path('api/delete_slide', views.DeleteSlide.as_view(), name="delete_slide"),


    path('api/delete_all_slides', views.DeleteAllSlides.as_view(), name="delete_all_slides"),
    path('api/delete_all_boards', views.DeleteAllBoards.as_view(), name="delete_all_boards"),

    path('api/update_board', views.UpdateBoard.as_view(), name="update_board"),
    path('api/update_board_slide', views.UpdateBoardSlide.as_view(), name="update_board_slide"),

    # path('api/generate_text', views.GenerateTextView.as_view(), name="generate_text"),
    # path('api/generate_text', views.GenerateTextView.as_view(), name="generate_text"),
    # path('api/generate_text', views.GenerateTextView.as_view(), name="generate_text"),


    # path('register/', views.register, name='register'),
    # path('login/', views.login, name='login'),
    # path('logout/', views.logout, name='logout'),
]

krock/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    login_view,
    logout_view,
    forgot_password_view,
    registeration_view,
    check_otp_view,
    check_reset_otp_view,
    reset_new_password_view,
)

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('sign_in/', login_view, name='sign_in'),
    path('logout/', logout_view, name='logout'),
    path('sign_up/', registeration_view, name='sign_up'),
    path('forgot-password/', forgot_password_view, name='forgot_password'),
    path('activate-email/', check_otp_view, name='activate_email'),
    path('reset-code/', check_reset_otp_view, name='reset_code'),
    path('new-password/', reset_new_password_view, name='reset_new_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from os import path


def get_profile_picture_filepath(instance, filename):
    filename = filename.split('.')[-1]
    return path.join('profile_images', '{}profile_image.{}'.format(instance.pk, filename))


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(
        _('profile picture'), upload_to=get_profile_picture_filepath, null=True, blank=True)
    bio = models.TextField(_('Bio'), max_length=500, blank=True)
    short_bio = models.TextField(_('Short Bio'), max_length=250, blank=True)
    source = models.CharField(_('source'), max_length=50, blank=True)
    balance = models.IntegerField(_('Balance'), default=0)

    
class OtpCode(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)

    def __str__(self):
        return self.code

users/forms.py
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import widgets
from django.utils.translation import gettext_lazy as _
from django.core.validators import validate_email
from django import forms
from users.models import OtpCode


class CustomLoginForm(forms.Form):
    username_or_email = forms.CharField(max_length=256, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username or Email'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))

    def clean_username_or_email(self):
        username_or_email = self.cleaned_data['username_or_email']
        if "@" in username_or_email:
            validate_email(username_or_email)
            data = {'email': username_or_email}
        else:
            data = {'username': username_or_email}
        try:
            get_user_model().objects.get(**data)
        except get_user_model().DoesNotExist:
            raise ValidationError(
                _('This {} does not exist'.format(list(data.keys())[0])))
        else:
            return username_or_email


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget = widgets.TextInput(
            attrs={'placeholder': "username", "class": "form-control"})
        self.fields['email'].widget = widgets.EmailInput(
            attrs={'placeholder': "email", "class": "form-control"})
        self.fields['password1'].widget = widgets.PasswordInput(
            attrs={'placeholder': "password", "class": "form-control"})
        self.fields['password2'].widget = widgets.PasswordInput(
            attrs={'placeholder': "repeat password", "class": "form-control"})

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise ValidationError("This email address is already exists.")
        return email

    class Meta:
        model = get_user_model()
        fields = ("username", "email")


class ForgetPasswordEmailCodeForm(forms.Form):
    username_or_email = forms.CharField(max_length=256,
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control',
                                                   'placeholder': 'Type your email'}
                                        )
                                        )

    def clean_username_or_email(self):
        username_or_email = self.cleaned_data['username_or_email']
        data = {'username': username_or_email}

        if '@' in username_or_email:
            validate_email(username_or_email)
            data = {'email': username_or_email}
        try:
            get_user_model().objects.get(**data)
        except get_user_model().DoesNotExist:
            raise ValidationError(
                'There is no account with this {}'.format(list(data.keys())[0]))

        if not get_user_model().objects.get(**data).is_active:
            raise ValidationError(_('This account is not active.'))

        return data


class ChangePasswordForm(forms.Form):
    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'New password'
            }
        ),
    )
    new_password2 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Confirm password',
            }
        ),
    )

    def clean_new_password2(self):
        password1 = self.cleaned_data['new_password1']
        password2 = self.cleaned_data['new_password2']

        if password1 and password2 and password1 != password2:
            raise ValidationError(_('Passwords are not match'))
        password_validation.validate_password(password2)
        return password2


class OtpForm(forms.Form):
    otp = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter code',
            }
        )
    )

    def clean_otp(self):
        otp_code = self.cleaned_data['otp']
        try:
            OtpCode.objects.get(code=otp_code)
        except OtpCode.DoesNotExist:
            raise ValidationError(
                _('You have entered incorrect code!')
            )
        else:
            return otp_code

users/views.py
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
from django.contrib.auth.hashers import make_password
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django.utils.crypto import get_random_string
from django.shortcuts import (
    redirect,
    render,
)
from django.views import View

from django.contrib.auth.decorators import login_required

from .forms import (
    CustomLoginForm,
    RegisterForm,
    ForgetPasswordEmailCodeForm,
    ChangePasswordForm,
    OtpForm,
)
from .models import OtpCode, CustomUser
from .utils import (
    send_activation_code,
    send_reset_password_code,
)
from .decorators import only_authenticated_user, redirect_authenticated_user

class Home(View):
    template = "home.html"
    def get(self, request, *args, **kwargs):
        context = {}
        return render(self.request, self.template, context)

@redirect_authenticated_user
def login_view(request):
    error = None
    if request.method == 'POST':
        form = CustomLoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request, username=form.cleaned_data['username_or_email'], password=form.cleaned_data['password'])
            if user:
                if user.is_active:  #                 if not user.is_active:
                    messages.warning(request, _(
                        f"It's look like you haven't still verify your email - {user.email}"))
                    return redirect('users:activate_email')
                else:
                    login(request, user)
                    return redirect('app:app_panel')
            else:
                error = 'Invalid Credentials'
    else:
        form = CustomLoginForm()
    return render(request, 'users/sign_in.html', {'form': form, 'error': error})


@only_authenticated_user
@login_required
def logout_view(request):
    logout(request)
    return redirect('users:sign_in')


@redirect_authenticated_user
def registeration_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.source = 'Register'
            user.save(True)

            # code = get_random_string(20)
            # otp = OtpCode(code=code, user=user)
            # otp.save(True)
            # try:
            #     send_activation_code(user.email, code)
            # except:
            #     otp.delete()
            #     user.delete()
            #     messages.error(request, _('Failed while sending code!'))
            # else:
            #     messages.success(
            #         request, _(f'We have sent a verification code to your email - {user.email}'))

            return redirect('users:sign_in')
                # return redirect('users:activate_email')
    else:
        form = RegisterForm()
    return render(request, 'users/sign_up.html', {'form': form})


@redirect_authenticated_user
def forgot_password_view(request):
    if request.method == 'POST':
        form = ForgetPasswordEmailCodeForm(request.POST)
        if form.is_valid():
            username_or_email = form.cleaned_data['username_or_email']
            user = get_user_model().objects.get(**username_or_email)
            code = get_random_string(20)

            otp = OtpCode(code=code, user=user, email=user.email)
            otp.save()

            try:
                send_reset_password_code(user.email, code)
            except:
                otp.delete()
                messages.error(request, _('Failed while sending code!'))
            else:
                messages.success(request, _(
                    f"We've sent a passwrod reset otp to your email - {user.email}"))
                return redirect('users:reset_code')
    else:
        form = ForgetPasswordEmailCodeForm()
    return render(request, 'users/forgot_password.html', context={'form': form})

@redirect_authenticated_user
def check_otp_view(request):
    if request.method == 'POST':
        form = OtpForm(request.POST)
        if form.is_valid():
            otp = OtpCode.objects.get(code=form.cleaned_data['otp'])
            user = otp.user
            otp.delete()
            user.is_active = True
            user.save()
            return redirect('users:sign_in')
    else:
        form = OtpForm()
    return render(request, 'users/user_otp.html', {'form': form})

@redirect_authenticated_user
def check_reset_otp_view(request):
    if request.method == 'POST':
        form = OtpForm(request.POST)
        if form.is_valid():
            otp = OtpCode.objects.get(code=form.cleaned_data['otp'])
            request.session['email'] = otp.user.email
            messages.success(request, _(
                "Please create a new password that you don't use on any other site."))
            return redirect('users:reset_new_password')
    else:
        form = OtpForm()
    return render(request, 'users/user_otp.html', {'form': form})


@redirect_authenticated_user
def reset_new_password_view(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            email = request.session['email']
            del request.session['email']
            user = CustomUser.objects.get(email=email)
            user.password = make_password(form.cleaned_data["new_password2"])
            user.save()
            messages.success(request, _(
                "Your password changed. Now you can login with your new password."))
            return redirect('users:sign_in')
    else:
        form = ChangePasswordForm()
    return render(request, 'users/new_password.html', {'form': form})

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{% block title %} {% endblock %}</title>

      {% load static %}
      <!-- CSS files -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,700">
      <script src="{% static 'js/tabler.min.js' %}"></script>
      <link rel="stylesheet" href="{% static 'css/tabler.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/tabler-flags.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/tabler-payments.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/tabler-vendors.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <style>
      @import url('https://rsms.me/inter/inter.css');
      :root {
      	--tblr-font-sans-serif: 'Inter Var', -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;
      }
      body {
      	font-feature-settings: "cv03", "cv04", "cv11";
      }
    </style>


   </head>
   <body>

      {% block navbar %}{% endblock navbar %}



      {% block content %}{% endblock %}

   </body>
</html>

users/templates/users/forgot_password.html
{% extends "./base.html" %}
{% load static %}

{%block title%}
Password reset
{%endblock title%}

{% block content %}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}

<div class=" d-flex flex-column">
    <script src="./dist/js/demo-theme.min.js?1685976846"></script>
    <div class="page page-center">
      <div class="container container-tight py-4">
        <div class="text-center mb-4">
          <a href="." class="navbar-brand navbar-brand-autodark"><img src="./static/logo.svg" height="36" alt=""></a>
        </div>

        <form class="card card-md" action="./" method="get" autocomplete="off" novalidate="">
            {%csrf_token%}
          <div class="card-body">
            <h2 class="card-title text-center mb-4">Forgot password</h2>
            <p class="text-muted mb-4">Enter your email address and your password will be reset and emailed to you.</p>
            <div class="mb-3">
              <label class="form-label">Email address</label>
              {% for field in form %}
              <div class="form-group mb-3">
                  {{field}}
                  {% if field.errors %}
                  {% for error in field.errors %}
                  <span class="invalid-feedback {%if error%}d-block{%endif%}">{{error}}</span>
                  {% endfor %}
                  {%endif%}
              </div>
              {% endfor %}
              <!-- <input type="email" class="form-control" placeholder="Enter email"> -->
            </div>
            <div class="form-footer">
              <a href="#" class="btn btn-primary w-100">
                <!-- Download SVG icon from http://tabler-icons.io/i/mail -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10z"></path><path d="M3 7l9 6l9 -6"></path></svg>
                Send me new password
              </a>
            </div>
          </div>
        </form>
        <div class="text-center text-muted mt-3">
          Forget it, <a href="{% url 'users:sign_in' %}">send me back</a> to the sign in screen.
        </div>
      </div>
    </div>
</div>
{%endblock content %}

users/templates/users/form_snippets.html
<div class="row lg-3">
    <div class="col-sm-6 {%if center%} mx-auto {%endif%}">
        {% for field in form %}
        <div class="form-group mb-3">
            {{field}}
            {% if field.errors %}
            {% for error in field.errors %}
            <span class="invalid-feedback {%if error%}d-block{%endif%}">{{error}}</span>
            {% endfor %}
            {%endif%}
        </div>
        {% endfor %}
    </div>    
</div>

users/templates/users/home.html
{% extends 'shared_layout/base.html' %}

users/templates/users/login.html
<!DOCTYPE html>
{% extends 'shared_layout/base.html' %}

{%block title%}
login
{%endblock title%}

{%block contents%}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<form method="post">
    {%csrf_token%}
    {%include 'users/form_snippets.html' with form=form%}                
    <input class="btn btn-primary" type="submit" value="Login">
</form>
<div class="my-2">
    <small class="text-muted">
        Forgot your password ? <a class="ml-2" href="{%url 'users:forgot_password'%}">restore password</a>
    </small>
</div>

<div class="my-2">
    <small class="text-muted">
        Need an account ? <a class="ml-2" href="{%url 'users:register'%}">Sign Up</a>
    </small>
</div>
{%endblock contents%}

users/templates/users/new_password.html
<!DOCTYPE html> {% extends 'shared_layout/base.html' %} 
{%block title%}Create a new password{%endblock title%} 
{%block contents%} 
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<div class="row">
    <div class="col-12 text-center">
        <h5 class="m-2">Reset new password</h5>
        <p class="text-muted">
            Please enter your new password twice so we can verify you typed it in correctly.
        </p>
        <form method="post">
            {%csrf_token%} {%include 'users/form_snippets.html' with center=True form=form%}
            <input class="btn btn-primary" type="submit" value="Change your password">
        </form>
    </div>
</div>
{%endblock contents%}

users/templates/users/register.html
<!DOCTYPE html> {% extends 'shared_layout/base.html' %} {%block title%} register {%endblock title%} {%block contents%} {%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<form method="post">
    {%csrf_token%} {%include 'users/form_snippets.html' with form=form%}
    <input class="btn btn-primary" type="submit" value="Register">
</form>
<div class="my-2">
    <small class="text-muted">
        Forgot your password ? <a class="ml-2" href="{%url 'users:forgot_password'%}">restore password</a>
    </small>
</div>

<div class="my-2">
    <small class="text-muted">
        Already have an account ? <a class="ml-2" href="{%url 'users:login'%}">Sign In</a>
    </small>
</div>
{%endblock contents%}

users/templates/users/sign_in.html
{% extends "./base.html" %}
{% load static %}


{% block content %}
<div class="d-flex flex-column">
    <div class="page page-center">
        <div class="container container-tight py-4">
          <div class="card card-md">
            <div class="card-body">
              <h2 class="h2 text-center mb-4">Login to your account</h2>
              <form method="post" autocomplete="off" novalidate="">
                {%csrf_token%}
                {% for field in form %}
                <div class="form-group mb-3">
                  <label class="form-label">{{field.name}}</label>
                    {{field}}
                    {% if field.errors %}
                    {% for error in field.errors %}
                    <span class="invalid-feedback {%if error%}d-block{%endif%}">{{error}}</span>
                    {% endfor %}
                    {%endif%}
                </div>
                {% endfor %}
                <div class="mb-3">
                  <span class="form-label-description">
                    <a href="{%url 'users:forgot_password'%}">I forgot password</a>
                  </span>
                </div>

                <div class="form-footer">
                  <input class="btn btn-primary w-100" type="submit" value="Sign in">
                </div>
              </form>
            </div>
            <div class="hr-text">or</div>
            <div class="card-body">
              <div class="row">
                <div class="col"><a href="#" class="btn w-100">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon text-github" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5"></path></svg>
                    Login with Github
                  </a></div>
                <div class="col"><a href="#" class="btn w-100">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon text-twitter" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M22 4.01c-1 .49 -1.98 .689 -3 .99c-1.121 -1.265 -2.783 -1.335 -4.38 -.737s-2.643 2.06 -2.62 3.737v1c-3.245 .083 -6.135 -1.395 -8 -4c0 0 -4.182 7.433 4 11c-1.872 1.247 -3.739 2.088 -6 2c3.308 1.803 6.913 2.423 10.034 1.517c3.58 -1.04 6.522 -3.723 7.651 -7.742a13.84 13.84 0 0 0 .497 -3.753c0 -.249 1.51 -2.772 1.818 -4.013z"></path></svg>
                    Login with Twitter
                  </a></div>
              </div>
            </div>
          </div>
          <div class="text-center text-muted mt-3">
            Don't have account yet? <a href="{%url 'users:sign_up'%}" tabindex="-1">Sign up</a>
          </div>
        </div>
  </div>
</div>
{% endblock %} 

users/templates/users/sign_up.html
{% extends "./base.html" %} 

{% load static %} 

{% block content %}
<div class="page page-center">
  <div class="container container-tight py-4">
    <form class="card card-md" method="post" autocomplete="off" novalidate="">
      <div class="card-body">
        <h2 class="card-title text-center mb-4">Create new account</h2>
        {%csrf_token%} {% for field in form %}
        <div class="form-group mb-3">
          <label class="form-label">{{field.name}}</label>
          {{field}} {% if field.errors %} {% for error in field.errors %}
          <span class="invalid-feedback {%if error%}d-block{%endif%}"
            >{{error}}</span
          >
          {% endfor %} {%endif%}
        </div>
        {% endfor %}

        <div class="mb-3">
          <label class="form-check">
            <input type="checkbox" class="form-check-input" />
            <span class="form-check-label"
              >Agree the
              <a href="./terms-of-service.html" tabindex="-1"
                >terms and policy</a
              >.</span
            >
          </label>
        </div>
        <div class="form-footer">
          <input class="btn btn-primary w-100" type="submit" value="Sign Up" />
        </div>
      </div>
    </form>
    <div class="text-center text-muted mt-3">
      Already have account?
      <a href="{% url 'users:sign_in' %}" tabindex="-1">Sign in</a>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/user_otp.html
{% extends "./base.html" %} {% load static %}

{%block title%}
Code Verification
{%endblock title%}

{%block contents%}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<div class="row">
    <div class="col-12 text-center">
        <h5 class="m-2">Code Verification</h5>
        <p class="text-muted">
            Enter the code witch has been sent to you.
        </p>
        <form method="post">
            {%csrf_token%}
            {%include 'users/form_snippets.html' with center=True form=form%}             
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>    
    </div>
</div>
{%endblock contents%}